// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef heatmap_h
#define heatmap_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_File_Input.H>
#include <FL/Fl_File_Browser.H>
extern void about_callback(Fl_Button*, void*);
#include <FL/Fl_Check_Button.H>
#endif
