// Copyright (C) 2014-2015 Bohdan Khomtchouk and Derek Van Booven

// This file is part of HeatmapGenerator.

// This C code contains the necessary preprocessor directives for successfully compiling HeatmapGenerator on Mac OS X and Windows OS.

// BK wishes to acknowledge full financial support by the United States Department of Defense (DoD) through the National Defense Science and Engineering Graduate Fellowship (NDSEG) Program: this research was conducted with Government support under and awarded by DoD, Army Research Office (ARO), National Defense Science and Engineering Graduate (NDSEG) Fellowship, 32 CFR 168a.

// Please cite: "Khomtchouk et al.: HeatmapGenerator: high performance RNAseq and microarray visualization software suite to examine differential gene expression levels using an R and C++ hybrid computational pipeline. Source Code for Biology and Medicine 2014 9:30" within any source that makes use of any methods inspired by HeatmapGenerator.

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// ------------------------------------------------------------------------------------

// HeatmapGenerator binary executable is generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef heatmap_h
#define heatmap_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_File_Input.H>
#include <FL/Fl_File_Browser.H>
extern void about_callback(Fl_Button*, void*);
#include <FL/Fl_Check_Button.H>
#endif
